version: '2'
networks:
  luigi-net:

services:
  scheduler:
    image: spiside/luigi:latest
    ports:
      - "8082:8082"
    environment:
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgres://luigi@db/dev
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: "true"
    depends_on:
      - db
    entrypoint:
      - ./wait-for-postgres.sh
      - db
    networks:
      luigi-net:

  worker:
    build:
      dockerfile: docker/Dockerfile.worker
      context: .
    hostname: worker
    volumes:
      - .:/luigi
    environment:
      LUIGI_CORE_DEFAULT-SCHEDULER-URL: http://scheduler:8082
    depends_on:
      - scheduler
    networks:
      luigi-net:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: luigi
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
    networks:
      luigi-net:
